replicaCount: 1
revisionHistoryLimit: 3
env:
  # AUTH_TYPE: "basic"
  # BASIC_AUTH_USER: "admin"

image:
  repository: lmenezes/cerebro
  # Note: when updating the version, ensure `config` and the ConfigMap are kept
  # in sync with the default configuration of the upstream image
  tag: 0.9.2
  pullPolicy: IfNotPresent

deployment:
  # additional labels
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  labels: {}
  path: /
  hosts:
    - cerebro.silkrode.in
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

priorityClassName: ""

resources: {}

nodeSelector: {}

tolerations: 
  - key: "preemptible"
    operator: "Equal"
    value: "true"
    effect: "PreferNoSchedule"
  - key: "preemptible"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

affinity: 
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
            - preemptible
  # Anti-affinity to disallow deploying client and master nodes on the same worker node
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchLabels:
            app: cerebro

# Reference to a Secret object with environment variables
# envFromSecretRef: 'my-secret-ref'

config:
  basePath: '/'
  restHistorySize: 50
  hosts: 
    - host: http://prod-project1-elasticsearch.gcp.silkrode.com.tw
      name: prod-project1
    - host: http://sit-project1-elasticsearch.gcp.silkrode.com.tw
      name: sit-project1
    - host: http://prepod-gam-graylog.gcp.silkrode.com.tw:9200
      name: prod-gam
    - host: http://prod-project2-elasticsearch.gcp.silkrode.com.tw
      name: prod-project2
    - host: http://prod-project3-elasticsearch.gcp.silkrode.com.tw
      name: prod-project3
    - host: http://sit-project3-elasticsearch.gcp.silkrode.com.tw
      name: sit-project3
    - host: http://prod-project4-elasticsearch.gcp.silkrode.com.tw
      name: prod-project4
    - host: http://sit-project4-elasticsearch.gcp.silkrode.com.tw
      name: sit-project4
    - host: http://prod-project5-elasticsearch.gcp.silkrode.com.tw
      name: prod-project5
    - host: http://sit-project5-elasticsearch.gcp.silkrode.com.tw
      name: prod-mobile
    - host: http://sit-project2-elasticsearch.gcp.silkrode.com.tw


  # Secret used to sign session cookies. If empty it will be replaced with a
  # random 64 length string
  secret: ''
  tlsVerify: true
  # tlsCaCert: /opt/cerebro/conf/certs/ca.crt

# volumeMounts:
#   - mountPath: /opt/cerebro/conf/certs/
#     name: ca_cert_volume
#     readOnly: true
# volumes:
#   - name: ca_cert_volume
#     secret:
#       defaultMode: 420
#       optional: false
#       secretName: cerebro_ca_cert_secret