apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elasticsearch

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: gcs-key
  files:
    - gcs.client.default.credentials_file=silkrode-elasticsearch-backup.json
